LOADOUTS = [];
SELECTED_LOADOUT = -1;
CURRENT_TAB_IS_SELECT = true;
SWAPPING_LOADOUTS = false;
ALLOW_KEYBOARD_SHORTCUTS = true;

CHARCODE_MIN_NUMBER = 48;
CHARCODE_MAX_NUMBER = 57;
CHARCODE_MIN_NUMPAD = 96;
CHARCODE_MAX_NUMPAD = 105;
CHARCODE_HYPHEN = 189;
CHARCODE_QUESTION = 191;
CHARCODE_A = 65;
CHARCODE_S = 83;
CHARCODE_D = 68;
CHARCODE_ENTER = 13;
