LOADOUTS = [];
HOME = true;
CHARCODE_MIN_NUMBER = 48;
CHARCODE_MAX_NUMBER = 57;
CHARCODE_MIN_NUMPAD = 96;
CHARCODE_MAX_NUMPAD = 105;
CHARCODE_HYPHEN = 189
SELECTED_LOADOUT = -1;
UNUSED_LOADOUT = true;
SWAP = false;

COLORS = {
  "blue": "#75A4F4",


}
