var LOADOUTS = [];
var SELECTED_LOADOUT = -1;
var CURRENT_TAB_IS_SELECT = true;
var SWAPPING_LOADOUTS = false;
var ALLOW_KEYBOARD_SHORTCUTS = true;

const CHARCODE_MIN_NUMBER = 48;
const CHARCODE_MAX_NUMBER = 57;
const CHARCODE_MIN_NUMPAD = 96;
const CHARCODE_MAX_NUMPAD = 105;
const CHARCODE_HYPHEN = 189;
const CHARCODE_QUESTION = 191;
const CHARCODE_A = 65;
const CHARCODE_S = 83;
const CHARCODE_D = 68;
const CHARCODE_ENTER = 13;
